---

- hosts: all
  remote_user: root
  serial: 1
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: "{{ item }}"
        allow_unauthenticated: yes
      with_items:
        - sudo
        - dirmngr
        - software-properties-common
        - apt-transport-https

    - name: Add mariadb key
      apt_key:
       id: F1656F24C74CD1D8
       url: https://mariadb.org/mariadb_release_signing_key.asc
       state: present    

    - name: add mariadb repo
      apt_repository:
       repo: 'deb [arch=amd64,i386,ppc64el] https://ftp.harukasan.org/mariadb/repo/10.4/debian stretch main'
       state: present  

    - name: Run "apt-get update"
      apt:
        update_cache: yes

    - name: Install mariadb-server
      apt:
        name: mariadb-server
        state: present    

    - name: Install rsync
      apt:
        name: rsync
        state: present   

    - name: create deploy template
      template:
        src: galera.cnf.j2
        dest: /etc/mysql/conf.d/galera.cnf
        
    - name: stop mysql service
      service:
        name: "mysql"
        state: "stopped"
        
    - name: Start first node
      shell: galera_new_cluster
      when: inventory_hostname == groups['servers'][0]

    - name: start and enable mysql one by one
      service:
        name: "mysql"
        state: "started"
        enabled: true
      when: inventory_hostname != groups['servers'][0]
